---
title: "HW3"
author: "Eleonore Durand and Teresa Fukuda"
date: "May 17, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load packages and read in data

library(tidyverse)
library(stargazer)

surveydata<- read_csv("HW3Data.csv") %>% 
  mutate(Risk = risk/100
  ) %>% 
  select(Risk, bid, vote, NEP, income, age)




```

```{r, results="asis"}
#1. Create a linear model

yeslm<- lm(vote ~ Risk + bid + NEP + income + age, data=surveydata)
yeslm
#intercept: 0.119698
# Risk: 0.074449
#bid: -0.001070
#NEP: 0.015864
#middle is reference level for income 
#income1% : 0.008828
#incomepoor: 0.002739
#incomerich: 0.007489
#incomevery rich: 0.046792
#age oversixty is reference level
#tofifty: 0.009982
#toforty: -0.020119
#tosixty: -0.016226 
#tothirty: 0.020440

summary(yeslm)

stargazer(yeslm, type = "html")

```

```{r}
#2. calculate the value of a whale death
#4% risk reduction is for one whale -- use the linear regression to calculate the change in predicted bidi when risk is reduced by 4% (the model is linear so can take this from any two points on the model, all else the same?)

#store coefficients as variables

interceptcoef <- yeslm$coefficients[1]
riskcoef <- yeslm$coefficients[2]
bidcoef<- yeslm$coefficients[3]
nepcoef<- yeslm$coefficients[4]
income1pctcoef <- yeslm$coefficients[5]
poorcoef <- yeslm$coefficients[6]
richcoef <- yeslm$coefficients[7]
veryrichcoef <- yeslm$coefficients[8]
to50coef <- yeslm$coefficients[9]
to40coef <- yeslm$coefficients[10]
to60coef <- yeslm$coefficients[11]
to30coef <- yeslm$coefficients[12]

# probyes= interceptcoef + riskcoef* risk+ bidcoef*bid + nepcoef*nep+ income1pctcoef*income1pct + poorcoef*poor+ richcoef*rich + veryrichcoef*very rich + to50coef*to50 + to40coef * to40 + to60coef*to60 + to30coef*to30

#bid*bidcoef= interceptcoef + riskcoef* risk+ nepcoef*nep+ income1pctcoef*income1pct + poorcoef*poor+ richcoef*rich + veryrichcoef*very rich + to50coef*to50 + to40coef * to40 + to60coef*to60 + to30coef*to30- probyes
 
#bid= (interceptcoef + riskcoef* risk+ nepcoef*nep+ income1pctcoef*income1pct + poorcoef*poor+ richcoef*rich + veryrichcoef*very rich + to50coef*to50 + to40coef * to40 + to60coef*to60 + to30coef*to30- probyes)/-bidcoef


predicteddata <- surveydata %>% 
  mutate(probresponse= predict(yeslm, newdata=surveydata, type="response"))

#person we chose: 80= (interceptcoef + riskcoef* 0.2+ nepcoef*15 + veryrichcoef*1 + to30coef*1- predicteddata$probresponse[1])/-bidcoef

#100= (interceptcoef + riskcoef* 0.4+ nepcoef*37 +  to30coef*1- predicteddata$probresponse[2])/-bidcoef

whalevalue= ((interceptcoef + riskcoef* 0.44+ nepcoef*37 +  to30coef*1- predicteddata$probresponse[2])/-bidcoef)-((interceptcoef + riskcoef* 0.4+ nepcoef*37 +  to30coef*1- predicteddata$probresponse[2])/-bidcoef)




bidlm<- lm(bid~ Risk + NEP+ income+ age + probresponse, data= predicteddata)

bidlm

predictedbidval <-predicteddata %>% 
   mutate(wtp= predict(bidlm, newdata=predicteddata, type="response"))

# 3. Pick three people and calculate their bids

person<- data.frame(Risk = 0.6, NEP = 15, income= "very_rich", age = "tothirty", probresponse = 0.5)

personbid <-predict(bidlm, newdata=person, type = "response")

person2<- data.frame(Risk = 0.6, NEP = 37, income= "middle", age = "tothirty", probresponse = 0.5)

personbid2 <-predict(bidlm, newdata=person2, type = "response")

person3 <- data.frame(Risk = 0.6, NEP = 32, income= "one_percent", age = "tothirty", probresponse = 0.5)

personbid3 <-predict(bidlm, newdata=person3, type = "response")

# 4. Calculate mean willingness to pay for 60% risk reduction for SB county households

final <-predicteddata %>% 
  select(NEP, income, age) %>% 
  mutate(probresponse = 0.5) %>% 
  mutate(Risk= 0.6) %>% 
   mutate(wtp= predict(bidlm, newdata=., type="response"))

meanwtp <- mean(final$wtp)

#5. Total benefit of all 150,000 households in SB County

totalbenefit <- meanwtp*150000

# 6. Net benefit

netbenefit <- totalbenefit -7000000
 
# 7. Cost of carbon
carboncost <- 50 

# 8. 

socialvalue <-totalbenefit
# consumers come out with benefit of 60% risk reduction
# producers come out the same (costs are compensated by the selling of carbon credit)
# social value = consumer welfare in whales saved 

```

